### ISSUE TITLE
Comparison to StrawberryPerl

### ISSUE THREAD

**Issue by sparticus1701** [cocoa-xu/perl-windows-build#1]
This is a question. My product currently uses StrawberryPerl, but pretty soon I need to be able to support Windows 11 on ARM and they don't have a build. It appears that you do.

Your build is significantly smaller than StrawberryPerl. Can you tell me why that may be?

**Comment by cocoa-xu** [comment]
Hi @sparticus1701, this build is mainly for me to compile OpenSSL on ARM64 Windows and it's built with all default options. Maybe some options are default to off and StrawberryPerl has them turned on, but take my words with a grain of salt as I didn't check the exact build commands in StrawberryPerl. :)
